apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-service-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-nginx-service-deploy
  template:
    metadata:
      labels:
        app: my-nginx-service-deploy
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
