apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-nginx-service-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
